#' tagObs
#'
#' A minimal function to mark observations use in a prior run lm() model. Observations will be marked with a new variable in the original data used in the lm() function.
#'
#' @param obj Model object generated by the lm() function.
#' @param tag Label with which to mark the used observations. Default is an indicator of 1.
#' @param name Optional name to assign to the suffix of the newly created varaible. Defualt is the model object name.
#' @examples
#' mod_1 <- lm(hp ~ disp + wt, data=mtcars)
#' tagObs(obj = mod_1)
#' @export
tagObs <- function(obj, tag=1, name=NULL){
  thisdf <- get(paste(eval(obj)$call$data))
  pars <- as.list(match.call()[-1])
  md <- as.character(pars$obj)
  n <- names(thisdf)
  i <- names(obj$fitted.values)

  #thisdf <- data.frame(thisdf[names(fitted.values(model)[i]),], tag) #Possible for use to create "Used obs and variables" dataframe....
  #thisdf[, length(thisdf)+1] <- 0
  thisdf[i, length(thisdf)+1] <- tag
  if(is.null(name)){
    names(thisdf) <- c(n, paste("In_Model_", md, sep=""))
  } else {
    names(thisdf) <- c(n, paste("In_Model_", name, sep=""))
  }
  thisdf
}
